version: '3.8'

services:
  react-app:
    image: test-landing-page
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
